# Generated by Django 5.0.7 on 2024-07-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("photo", models.ImageField(blank=True, upload_to="images/")),
                ("subtitle", models.CharField(max_length=400)),
                ("state", models.CharField(max_length=50)),
                ("years", models.CharField(max_length=50)),
                ("lenguage", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                ("hashtag", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Jangari"),
                            ("comedy", "Komedia"),
                            ("drama", "Drama"),
                            ("horror", "Qorqinchili"),
                            ("romance", "Romance"),
                            ("fantastik", "Fantastik"),
                            ("hayotiy", "hayotiy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cinema", "cinema"),
                            ("serila", "serial"),
                            ("multifilm", "multifilm"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "movia",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="rest.movia",
                    ),
                ),
            ],
        ),
    ]
