# Generated by Django 5.0.7 on 2024-07-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movia",
            old_name="lenguage",
            new_name="language",
        ),
        migrations.AlterField(
            model_name="movia",
            name="type",
            field=models.CharField(
                choices=[
                    ("cinema", "cinema"),
                    ("serial", "serial"),
                    ("multifilm", "multifilm"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="movia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="rest.movia",
            ),
        ),
    ]
