# Generated by Django 5.0.7 on 2024-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0002_rename_lenguage_movia_language_alter_movia_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movia",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "jangari"),
                    ("comedy", "komedia"),
                    ("drama", "drama"),
                    ("horror", "ujas"),
                    ("romance", "romance"),
                    ("fantastik", "fantastik"),
                    ("hayotiy", "hayotiy"),
                ],
                max_length=20,
            ),
        ),
    ]
