# Generated by Django 5.0.7 on 2024-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0006_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
