# Generated by Django 5.0.7 on 2024-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0009_remove_movia_views_count_video_views_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="views_count",
        ),
        migrations.AddField(
            model_name="movia",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
