# Generated by Django 5.0.7 on 2024-07-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0010_remove_video_views_count_movia_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="movia",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movia",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
