# Generated by Django 5.0.7 on 2024-07-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="video_file",
            field=models.FileField(default="", upload_to="videos/"),
            preserve_default=False,
        ),
    ]
