# Generated by Django 5.0.7 on 2024-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_cinema_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                    ("horror", "Horror"),
                    ("romance", "Romance"),
                    ("sci-fi", "Sci-Fi"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
