# Generated by Django 5.0.7 on 2024-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_alter_cinema_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "Jangari"),
                    ("comedy", "Komedia"),
                    ("drama", "Drama"),
                    ("horror", "Qorqinchili"),
                    ("romance", "Romance"),
                    ("fantastik", "Fantastik"),
                    ("hayotiy", "hayotiy"),
                ],
                max_length=20,
            ),
        ),
    ]
